# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-10 13:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0001_squashed_0004_auto_20160611_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='extra data'),
        ),
        migrations.AddField(
            model_name='version',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Points to parent (previous) version of the object.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reversion.Version'),
        ),
    ]
