# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-10 13:10
from __future__ import unicode_literals

from django.db import migrations, models


def fill_created_at(apps, scheme_editor):
    Version = apps.get_model('reversion', 'Version')
    for instance in Version.objects.select_related('revision').all():
        instance.created_at = instance.revision.date_created
        instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0002_auto_20190310_1310'),
    ]

    operations = [
        migrations.RunPython(fill_created_at),
    ]
