# Generated by Django 3.0.5 on 2020-05-16 19:55

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0004_version_reverted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='extra data'),
        ),
    ]
